import re

# We will define replacement dictionaries for GK, SCI, HIS
# Key: Question ID, Value: Tuple (q_id, cat, question, opA, opB, opC, opD, ans, exp, diff)

gk_replacements = [
    # Easy (001-120)
    ("GK014", "gk", "Which animal is the largest living primate on Earth?", "Gorilla", "Chimpanzee", "Orangutan", "Baboon", "Gorilla", "Gorillas are the largest living primates, with males weighing up to 200 kg.", "Easy"),
    ("GK027", "gk", "What is the tallest mammal living on land today?", "Elephant", "Giraffe", "Rhinoceros", "Hippopotamus", "Giraffe", "Giraffes are the tallest land mammals, reaching heights up to 5.8 meters.", "Easy"),
    ("GK039", "gk", "Which bird is famous for its inability to fly and its native habitat in Antarctica?", "Penguin", "Ostrich", "Kiwi", "Emu", "Penguin", "Penguins are flightless marine birds highly adapted to cold environments like Antarctica.", "Easy"),
    ("GK043", "gk", "Which fruit is famous for having its seeds located on the outside of its skin?", "Strawberry", "Apple", "Banana", "Blueberry", "Strawberry", "Strawberries are unique as their seeds (achenes) reside on the exterior skin.", "Easy"),
    ("GK045", "gk", "What is the capital city of Canada?", "Toronto", "Vancouver", "Ottawa", "Montreal", "Ottawa", "Ottawa was designated the official capital city of Canada in 1857.", "Easy"),
    ("GK058", "gk", "Which musical instrument has 88 keys in total on a standard keyboard?", "Accordion", "Piano", "Harpsichord", "Organ", "Piano", "A standard acoustic piano keyboard features 88 keys (52 white and 36 black).", "Easy"),
    ("GK060", "gk", "Which ocean is the largest and deepest on planet Earth?", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean", "Pacific Ocean", "The Pacific Ocean covers over 30% of Earth's surface and contains the deepest points.", "Easy"),
    ("GK063", "gk", "What primary color when combined with blue produces violet or purple?", "Red", "Yellow", "Green", "Orange", "Red", "Mixing primary colors red and blue in color theory yields purple.", "Easy"),
    ("GK066", "gk", "Which insect is famous for producing natural honey and honeycomb?", "Honeybee", "Butterfly", "Ladybug", "Dragonfly", "Honeybee", "Honeybees collect nectar from flowers to produce honey stored in honeycombs.", "Easy"),
    ("GK072", "gk", "Which famous tower in Italy is world-renowned for its unintended tilt?", "Leaning Tower of Pisa", "Eiffel Tower", "Big Ben", "CN Tower", "Leaning Tower of Pisa", "The campanile of Pisa cathedral tilted during construction due to soft ground.", "Easy"),
    ("GK101", "gk", "Which continent is home to the Amazon Rainforest?", "Africa", "South America", "Asia", "Australia", "South America", "The Amazon Rainforest covers most of the Amazon basin in South America.", "Easy"),
    ("GK102", "gk", "How many years are in one century?", "10", "50", "100", "1000", "100", "A century is a time period consisting of exactly 100 consecutive calendar years.", "Easy"),
    ("GK105", "gk", "Which fast land animal is recognized as the fastest land mammal on Earth?", "Cheetah", "Lion", "Leopard", "Gazelle", "Cheetah", "Cheetahs can reach sprint speeds of up to 100–120 km/h (60–75 mph).", "Easy"),
    ("GK120", "gk", "Which geometrical shape has three straight sides and three internal angles?", "Triangle", "Square", "Circle", "Pentagon", "Triangle", "A triangle is a three-sided polygon with interior angles summing to 180°.", "Easy"),

    # Medium (121-240)
    ("GK122", "gk", "Which canal connects the Pacific Ocean to the Atlantic Ocean in Central America?", "Panama Canal", "Suez Canal", "Erie Canal", "Kiel Canal", "Panama Canal", "The Panama Canal cuts across the Isthmus of Panama, connecting Atlantic and Pacific oceans.", "Medium"),
    ("GK129", "gk", "What is the capital city of Argentina?", "Buenos Aires", "Santiago", "Lima", "Bogota", "Buenos Aires", "Buenos Aires is the capital and largest city of Argentina.", "Medium"),
    ("GK130", "gk", "Which international peace organization replaced the League of Nations in 1945?", "United Nations", "NATO", "European Union", "INTERPOL", "United Nations", "The United Nations was established in 1945 following WWII to promote global cooperation.", "Medium"),
    ("GK133", "gk", "Which island is the largest non-continental island in the world by land area?", "Greenland", "Madagascar", "Borneo", "New Guinea", "Greenland", "Greenland is the world's largest island, covering over 2.16 million sq km.", "Medium"),
    ("GK139", "gk", "What is the capital city of New Zealand?", "Auckland", "Wellington", "Christchurch", "Hamilton", "Wellington", "Wellington replaced Auckland as the constitutional capital of New Zealand in 1865.", "Medium"),
    ("GK142", "gk", "Which museum in Paris is the world's largest art museum and houses the Mona Lisa?", "Louvre Museum", "Musée d'Orsay", "Centre Pompidou", "Prado Museum", "Louvre Museum", "The Louvre Museum in Paris is a historic monument and the world's most visited museum.", "Hard"),
    ("GK148", "gk", "What is the official currency of Mexico?", "Mexican Peso", "Sol", "Real", "Bolivar", "Mexican Peso", "The Mexican Peso (MXN) is the official currency of Mexico.", "Hard"),
    ("GK152", "gk", "How many teeth does a healthy adult human normally have including wisdom teeth?", "28", "30", "32", "36", "32", "Adult humans typically have 32 permanent teeth, including 4 wisdom teeth.", "Easy"),
    ("GK153", "gk", "Which gas is absorbed by green plants during the process of photosynthesis?", "Carbon Dioxide", "Oxygen", "Nitrogen", "Methane", "Carbon Dioxide", "Plants absorb atmospheric carbon dioxide and release oxygen during photosynthesis.", "Easy"),
    ("GK155", "gk", "Which planet is known as the Morning Star or Evening Star due to its brightness?", "Venus", "Mars", "Jupiter", "Mercury", "Venus", "Venus is the brightest natural object in the night sky after the Moon.", "Easy"),
    ("GK158", "gk", "What is the capital city of Spain?", "Madrid", "Barcelona", "Seville", "Valencia", "Madrid", "Madrid is the capital and most populous city of Spain.", "Easy"),
    ("GK160", "gk", "Which gas makes up approximately 78% of Earth's atmosphere by volume?", "Nitrogen", "Oxygen", "Argon", "Carbon Dioxide", "Nitrogen", "Nitrogen gas (N₂) accounts for roughly 78% of Earth's dry atmosphere.", "Easy"),
    ("GK161", "gk", "Which continent is the driest, windiest, and coldest continent on Earth?", "Antarctica", "Australia", "Africa", "Europe", "Antarctica", "Antarctica is a polar desert with lowest recorded temperatures and minimal precipitation.", "Easy"),
    ("GK167", "gk", "Which animal is the national symbol of Australia and carries its young in a pouch?", "Kangaroo", "Koala", "Emu", "Wombat", "Kangaroo", "The kangaroo is a native Australian marsupial featured on the Australian coat of arms.", "Easy"),
    ("GK168", "gk", "How many years are in a millennium?", "100", "500", "1000", "10000", "1000", "A millennium is a period of time equal to one thousand (1000) years.", "Easy"),
    ("GK170", "gk", "Which bamboo-eating bear is native to south-central China?", "Giant Panda", "Grizzly Bear", "Polar Bear", "Sloth Bear", "Giant Panda", "The giant panda is a bear species endemic to China, relying on bamboo for over 99% of its diet.", "Easy"),
    ("GK171", "gk", "What is the capital city of Switzerland?", "Bern", "Zurich", "Geneva", "Basel", "Bern", "Bern is the de facto federal capital city of Switzerland.", "Medium"),
    ("GK172", "gk", "Which straight line of zero degrees longitude passes through Greenwich, London?", "Prime Meridian", "Equator", "Tropic of Cancer", "International Date Line", "Prime Meridian", "The Prime Meridian is the line of 0° longitude dividing Eastern and Western Hemispheres.", "Medium"),
    ("GK175", "gk", "What is the capital city of South Africa's executive/administrative branch?", "Pretoria", "Cape Town", "Bloemfontein", "Johannesburg", "Pretoria", "South Africa has three capitals: Pretoria (executive), Cape Town (legislative), and Bloemfontein (judicial).", "Medium"),
    ("GK177", "gk", "What is the official currency unit used in South Korea?", "South Korean Won", "Yen", "Yuan", "Ringgit", "South Korean Won", "The South Korean Won (KRW) is the official currency of South Korea.", "Medium"),
    ("GK178", "gk", "Which famous scientist authored 'On the Origin of Species' introducing evolution by natural selection?", "Charles Darwin", "Gregor Mendel", "Louis Pasteur", "Isaac Newton", "Charles Darwin", "Charles Darwin published 'On the Origin of Species' in 1859 establishing evolutionary biology.", "Medium"),
    ("GK179", "gk", "What is the capital city of South Korea?", "Seoul", "Busan", "Incheon", "Daegu", "Seoul", "Seoul is the capital and financial heart of South Korea.", "Medium"),
    ("GK181", "gk", "Which desert is the largest hot desert in the world?", "Sahara Desert", "Gobi Desert", "Kalahari Desert", "Atacama Desert", "Sahara Desert", "The Sahara Desert in Northern Africa is the largest non-polar hot desert on Earth.", "Medium"),
    ("GK184", "gk", "What is the capital city of Turkey?", "Ankara", "Istanbul", "Izmir", "Bursa", "Ankara", "Ankara replaced Istanbul as the official capital of Turkey in 1923.", "Medium"),
    ("GK188", "gk", "What is the capital city of Greece?", "Athens", "Sparta", "Thessaloniki", "Heraklion", "Athens", "Athens is the capital and historical cradle of classical Greece.", "Medium"),
    ("GK190", "gk", "What is the official currency used in the United Kingdom?", "Pound Sterling", "Euro", "Franc", "Krona", "Pound Sterling", "The Pound Sterling (GBP) is the official currency of the United Kingdom.", "Medium"),

    # Hard (191-200, 241-300)
    ("GK192", "gk", "Which mountain peak in South America is the highest point outside of Asia?", "Aconcagua", "Ojos del Salado", "Huascarán", "Chimborazo", "Aconcagua", "Mount Aconcagua in Argentina (6,961 m) is the highest peak in both the Southern and Western Hemispheres.", "Hard"),
    ("GK193", "gk", "What is the capital city of Indonesia since its constitutional move to Nusantara?", "Jakarta", "Nusantara", "Surabaya", "Bandung", "Nusantara", "Nusantara in East Kalimantan was designated as the new capital city of Indonesia.", "Hard"),
    ("GK196", "gk", "Which global treaty signed in 1987 phased out ozone-depleting chlorofluorocarbons (CFCs)?", "Montreal Protocol", "Kyoto Protocol", "Paris Agreement", "Geneva Convention", "Montreal Protocol", "The Montreal Protocol on Substances that Deplete the Ozone Layer was agreed in 1987.", "Hard"),
    ("GK197", "gk", "What is the deepest lake in the world by depth, containing 20% of Earth's unfrozen surface fresh water?", "Lake Baikal", "Lake Tanganyika", "Lake Superior", "Caspian Sea", "Lake Baikal", "Lake Baikal in Siberia reaches a depth of 1,642 meters (5,387 ft).", "Hard"),
    ("GK199", "gk", "Which African nation was formerly known as Abyssinia?", "Ethiopia", "Sudan", "Somalia", "Eritrea", "Ethiopia", "Ethiopia was historically known in Western sources as Abyssinia.", "Hard"),
    ("GK200", "gk", "Which body of water is the saltiest landlocked lake on Earth with high buoyancy?", "Dead Sea", "Caspian Sea", "Lake Victoria", "Red Sea", "Dead Sea", "The Dead Sea is a hyper-saline lake between Israel and Jordan, over 8 times saltier than the ocean.", "Hard"),

    # Easy (201-220)
    ("GK201", "gk", "Which gas do humans inhale to stay alive through aerobic respiration?", "Oxygen", "Nitrogen", "Carbon Dioxide", "Helium", "Oxygen", "Oxygen is essential for cellular respiration in human metabolism.", "Easy"),
    ("GK204", "gk", "What is the freezing point of pure water in degrees Celsius at standard atmospheric pressure?", "0°C", "100°C", "32°C", "-10°C", "0°C", "Pure water freezes into ice at 0°C (32°F) under standard atmospheric conditions.", "Easy"),
    ("GK208", "gk", "Which imaginary horizontal line circles the Earth midway between North and South Poles at 0° latitude?", "Equator", "Prime Meridian", "Tropic of Capricorn", "Arctic Circle", "Equator", "The Equator divides the Earth into Northern and Southern Hemispheres.", "Easy"),
    ("GK209", "gk", "What is the capital city of Italy?", "Rome", "Milan", "Naples", "Florence", "Rome", "Rome is the capital city of Italy and was the heart of the Roman Empire.", "Easy"),
    ("GK210", "gk", "How many sides does a regular hexagon have?", "6", "5", "7", "8", "6", "A hexagon is a polygon with six straight sides and six vertices.", "Easy"),
    ("GK211", "gk", "Which major organ in human body filters waste from blood to produce urine?", "Kidney", "Liver", "Lungs", "Heart", "Kidney", "Kidneys filter blood plasma to excrete metabolic waste as urine.", "Easy"),
    ("GK213", "gk", "What is the capital city of Germany?", "Berlin", "Munich", "Frankfurt", "Hamburg", "Berlin", "Berlin is the capital and largest city of Germany.", "Easy"),

    # Medium (221-240)
    ("GK221", "gk", "Which sea is located between Europe and Africa and connected to Atlantic Ocean via Gibraltar?", "Mediterranean Sea", "Black Sea", "Red Sea", "Baltic Sea", "Mediterranean Sea", "The Mediterranean Sea lies between Southern Europe, Northern Africa, and Western Asia.", "Medium"),
    ("GK222", "gk", "What is the capital city of Ireland?", "Dublin", "Belfast", "Cork", "Galway", "Dublin", "Dublin is the capital and economic center of the Republic of Ireland.", "Medium"),
    ("GK223", "gk", "Which epic poem by Homer recounts the Greek siege of the city of Troy?", "Iliad", "Odyssey", "Aeneid", "Beowulf", "Iliad", "The Iliad is an ancient Greek epic poem attributed to Homer detailing the Trojan War.", "Medium"),
    ("GK225", "gk", "What is the official capital city of Brazil?", "Brasília", "Rio de Janeiro", "São Paulo", "Salvador", "Brasília", "Brasília was built in the interior and inaugurated as Brazil's capital in 1960.", "Medium"),
    ("GK227", "gk", "What is the capital city of Poland?", "Warsaw", "Krakow", "Gdansk", "Wroclaw", "Warsaw", "Warsaw is the capital and largest metropolis of Poland.", "Medium"),
    ("GK232", "gk", "What is the capital city of Norway?", "Oslo", "Bergen", "Trondheim", "Stavanger", "Oslo", "Oslo is the capital city and economic hub of Norway.", "Medium"),
    ("GK235", "gk", "What is the capital city of Sweden?", "Stockholm", "Gothenburg", "Malmo", "Uppsala", "Stockholm", "Stockholm is the capital and most populous urban area in Sweden.", "Medium"),
    ("GK240", "gk", "What is the capital city of Finland?", "Helsinki", "Tampere", "Turku", "Oulu", "Helsinki", "Helsinki is the capital and largest city of Finland.", "Medium"),

    # Hard (241-300)
    ("GK244", "gk", "Which landlocked country in Central Asia is the world's ninth-largest country by land area?", "Kazakhstan", "Uzbekistan", "Mongolia", "Turkmenistan", "Kazakhstan", "Kazakhstan is the largest landlocked country in the world.", "Hard"),
    ("GK245", "gk", "What is the capital city of Iceland?", "Reykjavik", "Akureyri", "Keflavik", "Kópavogur", "Reykjavik", "Reykjavik is the northernmost capital city of a sovereign state.", "Hard"),
    ("GK247", "gk", "What is the official currency of Switzerland?", "Swiss Franc", "Euro", "Krona", "Mark", "Swiss Franc", "The Swiss Franc (CHF) is the official currency of Switzerland and Liechtenstein.", "Hard"),
    ("GK249", "gk", "What is the capital city of Colombia?", "Bogotá", "Medellín", "Cali", "Cartagena", "Bogotá", "Bogotá is the high-altitude capital city of Colombia.", "Hard"),
    ("GK252", "gk", "Which famous structure in India was built by Emperor Shah Jahan as a mausoleum for his wife?", "Taj Mahal", "Qutub Minar", "Red Fort", "Gateway of India", "Taj Mahal", "The Taj Mahal in Agra was commissioned in 1832 by Shah Jahan for Mumtaz Mahal.", "Easy"),
    ("GK258", "gk", "What is the boiling point of pure water in degrees Celsius at standard atmospheric pressure?", "100°C", "0°C", "212°C", "50°C", "100°C", "Water boils at 100°C (212°F) under standard atmospheric pressure at sea level.", "Easy"),
    ("GK259", "gk", "Which continent is home to the Nile River, Sahara Desert, and Mount Kilimanjaro?", "Africa", "Asia", "South America", "North America", "Africa", "Africa contains the Nile, the Sahara, and Kilimanjaro.", "Easy"),
    ("GK261", "gk", "Which is the largest hot desert in North America covering parts of US and Mexico?", "Chihuahuan Desert", "Sonoran Desert", "Mojave Desert", "Great Basin Desert", "Chihuahuan Desert", "The Chihuahuan Desert is the largest hot desert in North America.", "Easy"),
    ("GK262", "gk", "Which red terrestrial planet is the fourth planet from the Sun in our solar system?", "Mars", "Venus", "Jupiter", "Mercury", "Mars", "Mars is the fourth planet from the Sun and second-smallest planet in solar system.", "Easy"),
    ("GK263", "gk", "What is the capital city of Belgium?", "Brussels", "Antwerp", "Ghent", "Bruges", "Brussels", "Brussels is the capital city of Belgium and headquarters of the EU.", "Easy"),
    ("GK264", "gk", "How many standard continents are recognized on planet Earth?", "7", "5", "6", "8", "7", "The 7 continents are Asia, Africa, North America, South America, Antarctica, Europe, Australia.", "Easy"),
    ("GK265", "gk", "Which gas is used by fire extinguishers to smother fires by displacing oxygen?", "Carbon Dioxide", "Oxygen", "Hydrogen", "Methane", "Carbon Dioxide", "CO₂ displaces oxygen and cools the fuel source in class B and C fires.", "Easy"),
    ("GK268", "gk", "What is the capital city of Thailand?", "Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Bangkok", "Bangkok is the capital and most populous city of Thailand.", "Easy"),
    ("GK269", "gk", "How many rings are featured on the official flag of the Olympic Games?", "5", "4", "6", "7", "5", "The 5 rings represent the five inhabited continents participating in the Olympic movement.", "Easy"),
    ("GK271", "gk", "What is the capital city of Denmark?", "Copenhagen", "Aarhus", "Odense", "Aalborg", "Copenhagen", "Copenhagen is the capital and most populous city of Denmark.", "Medium"),
    ("GK273", "gk", "Which artist painted 'The Last Supper' mural on the wall of Santa Maria delle Grazie?", "Leonardo da Vinci", "Michelangelo", "Raphael", "Caravaggio", "Leonardo da Vinci", "Leonardo da Vinci painted 'The Last Supper' in the late 15th century.", "Medium"),
    ("GK274", "gk", "Which strait connects the Atlantic Ocean to the Mediterranean Sea?", "Strait of Gibraltar", "Strait of Hormuz", "Bosporus Strait", "Bering Strait", "Strait of Gibraltar", "The Strait of Gibraltar connects the Atlantic Ocean to the Mediterranean Sea.", "Medium"),
    ("GK277", "gk", "What is the official currency of South Africa?", "South African Rand", "Kwanza", "Pula", "Cedi", "South African Rand", "The South African Rand (ZAR) is the legal tender of South Africa.", "Medium"),
    ("GK281", "gk", "What is the capital city of the Czech Republic?", "Prague", "Brno", "Ostrava", "Plzen", "Prague", "Prague is the capital and historic city of the Czech Republic.", "Medium"),
    ("GK282", "gk", "Which chemical symbol represents the element Gold on the periodic table?", "Au", "Ag", "Fe", "Cu", "Au", "Au comes from the Latin word for gold, 'aurum'.", "Medium"),
    ("GK284", "gk", "What branch of science deals with the study of living organisms and life processes?", "Biology", "Geology", "Astronomy", "Chemistry", "Biology", "Biology studies living organisms, structure, growth, evolution, and distribution.", "Medium"),
    ("GK285", "gk", "What is the capital city of Portugal?", "Lisbon", "Porto", "Coimbra", "Faro", "Lisbon", "Lisbon is the coastal capital city of Portugal.", "Medium"),
    ("GK286", "gk", "Which scientist discovered gravity after observing an apple falling from a tree?", "Isaac Newton", "Albert Einstein", "Galileo Galilei", "Nikola Tesla", "Isaac Newton", "Isaac Newton formulated the laws of motion and universal gravitation.", "Medium"),
    ("GK287", "gk", "What is the capital city of Hungary?", "Budapest", "Debrecen", "Szeged", "Pécs", "Budapest", "Budapest was formed by uniting Buda, Óbuda, and Pest across the Danube.", "Medium"),
    ("GK290", "gk", "What is the capital city of Austria?", "Vienna", "Salzburg", "Innsbruck", "Graz", "Vienna", "Vienna is the capital and largest city of Austria.", "Medium"),
    ("GK292", "gk", "Which mountain range contains Mount Everest, the world's highest peak above sea level?", "Himalayas", "Andes", "Rocky Mountains", "Alps", "Himalayas", "The Himalayas stretch across five countries and contain Mount Everest (8,848 m).", "Hard"),
    ("GK293", "gk", "What is the constitutional capital city of Bolivia?", "Sucre", "La Paz", "Cochabamba", "Santa Cruz", "Sucre", "Sucre is the constitutional capital, while La Paz is the seat of government.", "Hard"),
    ("GK295", "gk", "What is the official currency of Japan?", "Japanese Yen", "Won", "Yuan", "Ringgit", "Japanese Yen", "The Japanese Yen (JPY) is the third most traded currency in the foreign exchange market.", "Hard"),
    ("GK296", "gk", "What is the capital city of Egypt?", "Cairo", "Alexandria", "Giza", "Luxor", "Cairo", "Cairo is the capital and metropolitan heart of Egypt along the Nile.", "Hard"),
    ("GK297", "gk", "What is the capital city of the Netherlands?", "Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Amsterdam", "Amsterdam is the constitutional capital of the Netherlands.", "Hard"),
    ("GK299", "gk", "What is the capital city of Nepal located in the Kathmandu Valley?", "Kathmandu", "Pokhara", "Lalitpur", "Biratnagar", "Kathmandu", "Kathmandu is the capital and largest metropolis of Nepal.", "Hard"),
]

print(f"Generated GK replacement items: {len(gk_replacements)}")
