import re

sci_replacements = [
    # Easy (001-120)
    ("SCI030", "science", "Which metric unit of measurement is used to measure electrical current?", "Ampere", "Volt", "Ohm", "Watt", "Ampere", "The ampere (symbol A) is the SI base unit of electric current.", "Easy"),
    ("SCI037", "science", "What is the hardest naturally occurring gemstone material on Earth?", "Diamond", "Ruby", "Emerald", "Sapphire", "Diamond", "Diamond is an allotrope of carbon with the highest hardness on Mohs scale (10).", "Easy"),
    ("SCI050", "science", "Which tissue type in human blood carries oxygen to all cells via hemoglobin?", "Red Blood Cells", "White Blood Cells", "Platelets", "Plasma", "Red Blood Cells", "Red blood cells (erythrocytes) contain hemoglobin that binds and transports oxygen.", "Easy"),
    ("SCI052", "science", "What phenomenon causes light to bend when moving from air into glass or water?", "Refraction", "Reflection", "Diffraction", "Dispersion", "Refraction", "Refraction is the change in direction of a wave passing from one medium to another.", "Easy"),
    ("SCI063", "science", "What unit of force in the International System of Units (SI) is named after Isaac Newton?", "Newton", "Joule", "Pascal", "Watt", "Newton", "The newton (symbol N) is the SI unit of force, equal to 1 kg·m/s².", "Easy"),
    ("SCI069", "science", "What type of simple machine consists of a rigid beam pivoted at a fixed hinge or fulcrum?", "Lever", "Pulley", "Inclined Plane", "Wedge", "Lever", "A lever amplifies input force to provide mechanical advantage over a fulcrum.", "Easy"),
    ("SCI076", "science", "Which blood vessel type carries blood away from the heart toward body tissues?", "Arteries", "Veins", "Capillaries", "Venules", "Arteries", "Arteries carry oxygenated blood away from the heart (except pulmonary artery).", "Easy"),
    ("SCI101", "science", "Which component of the plant cell wall provides structural rigidity and strength?", "Cellulose", "Starch", "Glycogen", "Chitin", "Cellulose", "Cellulose is a complex carbohydrate forming structural cell walls in green plants.", "Easy"),
    ("SCI109", "science", "What biological process converts sugar into alcohol or acid anaerobically using yeast?", "Fermentation", "Respiration", "Transpiration", "Oxidation", "Fermentation", "Fermentation is an anaerobic metabolic pathway converting glucose into ethanol or lactic acid.", "Easy"),
    ("SCI116", "science", "Which rock type is formed from the cooling and solidification of molten magma or lava?", "Igneous", "Sedimentary", "Metamorphic", "Fossiliferous", "Igneous", "Igneous rocks (like basalt or granite) crystallize from molten rock material.", "Easy"),

    # Medium (121-240)
    ("SCI125", "science", "Which endocrine gland located at the base of the neck regulates metabolic rate via thyroid hormones?", "Thyroid Gland", "Adrenal Gland", "Pituitary Gland", "Pancreas", "Thyroid Gland", "The thyroid gland secretes T3 and T4 hormones controlling cellular metabolic speed.", "Medium"),
    ("SCI137", "science", "What physical property describes a material's opposition to the flow of electric current?", "Electrical Resistance", "Capacitance", "Inductance", "Conductance", "Electrical Resistance", "Electrical resistance (measured in ohms) quantifies resistance to charge movement.", "Medium"),
    ("SCI138", "science", "Which law of thermodynamics states that energy cannot be created or destroyed, only transformed?", "First Law of Thermodynamics", "Second Law of Thermodynamics", "Third Law of Thermodynamics", "Zeroth Law of Thermodynamics", "First Law of Thermodynamics", "The First Law expresses energy conservation: ΔU = Q - W.", "Medium"),
    ("SCI140", "science", "Which part of the human eye focuses incoming light rays onto the light-sensitive retina?", "Lens", "Cornea", "Iris", "Pupil", "Lens", "The crystalline lens fine-tunes light focusing onto the retina for sharp vision.", "Medium"),
    ("SCI156", "science", "Which state of matter consists of an ionized gas with free electrons and positive ions?", "Plasma", "Solid", "Liquid", "Gas", "Plasma", "Plasma is a high-energy state where gas atoms lose electrons, forming ionized gas.", "Medium"),
    ("SCI176", "science", "What is the speed of sound in dry air at room temperature (20°C) approximately?", "343 m/s", "1500 m/s", "300,000 m/s", "120 m/s", "343 m/s", "Sound travels at roughly 343 meters per second (1,235 km/h) in room-temperature air.", "Medium"),
    ("SCI201", "science", "Which instrument measures atmospheric pressure to predict weather changes?", "Barometer", "Hygrometer", "Anemometer", "Thermometer", "Barometer", "Barometers measure atmospheric pressure; falling pressure indicates approaching storms.", "Medium"),
    ("SCI205", "science", "Which fundamental force keeps atomic nuclei intact against electrostatic repulsion of protons?", "Strong Nuclear Force", "Weak Nuclear Force", "Electromagnetic Force", "Gravitational Force", "Strong Nuclear Force", "The strong nuclear force binds quarks and nucleons together inside atomic nuclei.", "Medium"),
    ("SCI216", "science", "Which nitrogenous base pairs exclusively with Adenine in RNA molecules instead of Thymine?", "Uracil", "Guanine", "Cytosine", "Thymine", "Uracil", "In RNA, Uracil (U) replaces Thymine (T) to complementary base-pair with Adenine (A).", "Medium"),
    ("SCI232", "science", "What term describes the maximum speed an object reaches falling through a fluid under gravity?", "Terminal Velocity", "Escape Velocity", "Orbital Speed", "Critical Speed", "Terminal Velocity", "Terminal velocity occurs when drag force equals gravitational downward force.", "Medium"),
    ("SCI234", "science", "Which cell structure synthesizes proteins by translating mRNA sequences?", "Ribosome", "Golgi Apparatus", "Endoplasmic Reticulum", "Mitochondria", "Ribosome", "Ribosomes translate genetic mRNA codons into amino acid polypeptide chains.", "Medium"),
    ("SCI237", "science", "Which scientific law states that total mass in an enclosed chemical reaction remains constant?", "Law of Conservation of Mass", "Law of Definite Proportions", "Avogadro's Law", "Dalton's Law", "Law of Conservation of Mass", "Formulated by Lavoisier, mass is neither created nor destroyed in chemical reactions.", "Medium"),
    ("SCI240", "science", "Which organ in the digestive system produces bile to emulsify fats?", "Liver", "Gallbladder", "Pancreas", "Stomach", "Liver", "The liver synthesizes bile, which is stored in the gallbladder and aids lipid digestion.", "Medium"),

    # Hard (241-300)
    ("SCI243", "science", "Which fundamental physical constant defines the quantum ratio of a photon's energy to its frequency?", "Planck's Constant", "Boltzmann Constant", "Avogadro Constant", "Rydberg Constant", "Planck's Constant", "Planck's constant h = 6.626×10⁻³⁴ J·s relates photon energy E to frequency f.", "Hard"),
    ("SCI246", "science", "Which ecological principle states two species competing for the exact same limited resource cannot coexist?", "Competitive Exclusion Principle", "Hardy-Weinberg Principle", "Gauss Principle", "Intermediate Disturbance Hypothesis", "Competitive Exclusion Principle", "Gause's principle states complete competitors cannot coexist at constant population densities.", "Hard"),
    ("SCI248", "science", "Which quantum phenomenon allows subatomic particles to pass through a potential barrier higher than their kinetic energy?", "Quantum Tunneling", "Quantum Entanglement", "Quantum Teleportation", "Wave Function Collapse", "Quantum Tunneling", "Quantum tunneling arises from the wave-like nature of particles penetrating barrier regions.", "Hard"),
    ("SCI251", "science", "Which thermodynamic law defines absolute zero where system entropy reaches a constant minimum?", "Third Law of Thermodynamics", "Zeroth Law of Thermodynamics", "First Law of Thermodynamics", "Second Law of Thermodynamics", "Third Law of Thermodynamics", "The Third Law states entropy of a pure crystalline substance approaches zero at 0 Kelvin.", "Hard"),
    ("SCI252", "science", "Which biochemical cycle converts acetyl-CoA into CO₂, NADH, and FADH₂ inside mitochondrial matrix?", "Citric Acid Cycle (Krebs Cycle)", "Calvin Cycle", "Glycolysis", "Pentose Phosphate Pathway", "Citric Acid Cycle (Krebs Cycle)", "The Krebs cycle oxidizes acetyl groups to generate energy carriers for ATP synthesis.", "Hard"),
    ("SCI254", "science", "Which equation expresses mass-energy equivalence formulated by Albert Einstein?", "E = mc²", "F = ma", "PV = nRT", "λ = h / p", "E = mc²", "Einstein's relativistic mass-energy formula states energy equals mass times light speed squared.", "Hard"),
    ("SCI256", "science", "Which primary lobe of the cerebral cortex processes visual information received from retina?", "Occipital Lobe", "Frontal Lobe", "Temporal Lobe", "Parietal Lobe", "Occipital Lobe", "The occipital lobe contains the primary visual cortex (V1) for visual processing.", "Hard"),
    ("SCI258", "science", "What optical effect describes sky blueness resulting from light scattering by atmospheric molecules?", "Rayleigh Scattering", "Mie Scattering", "Tyndall Effect", "Raman Scattering", "Rayleigh Scattering", "Rayleigh scattering scatters shorter blue wavelengths more efficiently than longer red wavelengths.", "Hard"),
    ("SCI262", "science", "Which subatomic particle made of three quarks is classified as a baryon?", "Proton", "Electron", "Neutrino", "Photon", "Proton", "Baryons are composite subatomic particles made of 3 valence quarks (protons = uud).", "Hard"),
    ("SCI265", "science", "Which law connects the current in a conductor directly to voltage across it at constant temperature?", "Ohm's Law", "Faraday's Law", "Ampere's Law", "Coulomb's Law", "Ohm's Law", "Ohm's law states current I is proportional to potential difference V (V = IR).", "Hard"),
    ("SCI282", "science", "Which rule predicts the major regioselective product in electrophilic addition to asymmetric alkenes?", "Markovnikov's Rule", "Zaitsev's Rule", "Hund's Rule", "Kornblum's Rule", "Markovnikov's Rule", "Markovnikov's rule states electrophile adds to carbon with more hydrogen atoms.", "Hard"),
    ("SCI286", "science", "Which fundamental principle in quantum mechanics states position and momentum cannot be measured simultaneously with arbitrary precision?", "Heisenberg Uncertainty Principle", "Pauli Exclusion Principle", "Aufbau Principle", "Schrödinger Equation", "Heisenberg Uncertainty Principle", "Heisenberg's principle states Δx Δp ≥ ℏ/2.", "Hard"),
    ("SCI288", "science", "Which cellular organelle synthesizes lipids, phospholipids, and steroid hormones while lacking ribosomes?", "Smooth Endoplasmic Reticulum", "Rough Endoplasmic Reticulum", "Golgi Apparatus", "Peroxisome", "Smooth Endoplasmic Reticulum", "SER synthesizes membrane lipids, metabolizes carbohydrates, and detoxifies chemicals.", "Hard"),
    ("SCI289", "science", "Which cosmological model posits the universe originated from an extremely dense hot singularity ~13.8 billion years ago?", "Big Bang Theory", "Steady State Model", "Plasma Cosmology", "Oscillating Universe", "Big Bang Theory", "The Big Bang theory explains the expansion and cosmic microwave background of our universe.", "Hard"),
    ("SCI290", "science", "Which mathematical equation in quantum mechanics governs how the wave function of a physical system evolves over time?", "Schrödinger Equation", "Maxwell's Equations", "Dirac Equation", "Navier-Stokes Equations", "Schrödinger Equation", "The Schrödinger equation governs non-relativistic quantum mechanical systems.", "Hard"),
    ("SCI291", "science", "Which law of electrodynamics states an induced electromotive force opposes the magnetic flux change that produced it?", "Lenz's Law", "Gauss's Law", "Biot-Savart Law", "Lorentz Force Law", "Lenz's Law", "Lenz's law specifies the direction of induced current, ensuring energy conservation.", "Hard"),
    ("SCI292", "science", "Which enzyme joins DNA fragments together by catalyzing phosphodiester bond formation during replication and repair?", "DNA Ligase", "DNA Polymerase", "RNA Polymerase", "Topoisomerase", "DNA Ligase", "DNA ligase seals nicks in the sugar-phosphate backbone, joining Okazaki fragments.", "Hard"),
]

his_replacements = [
    # Easy (001-120)
    ("HIS025", "history", "Who was the legendary ancient king of Macedon who created one of the largest empires in history by age 30?", "Alexander the Great", "Julius Caesar", "Xerxes I", "Hannibal", "Alexander the Great", "Alexander III of Macedon conquered Persia, Egypt, and northwestern India before dying at 32.", "Easy"),
    ("HIS027", "history", "Which French heroine and military leader turned the tide of the Hundred Years' War before being burned at the stake in 1431?", "Joan of Arc", "Marie Antoinette", "Eleanor of Aquitaine", "Catherine de' Medici", "Joan of Arc", "Joan of Arc rallied French forces against English occupation and was canonized as a saint.", "Easy"),
    ("HIS034", "history", "Which maritime explorer commanded the first Spanish expedition that successfully circumnavigated the globe from 1519 to 1522?", "Ferdinand Magellan", "Christopher Columbus", "Vasco da Gama", "Amerigo Vespucci", "Ferdinand Magellan", "Magellan led the Spanish expedition, completed by Juan Sebastián Elcano after Magellan's death.", "Easy"),
    ("HIS108", "history", "Which ancient Mesopotamian ruler formulated one of the earliest written legal codes featuring 'an eye for an eye'?", "Hammurabi", "Sargon of Akkad", "Nebuchadnezzar II", "Ashurbanipal", "Hammurabi", "The Code of Hammurabi of Babylon (c. 1750 BCE) contained 282 legal provisions.", "Easy"),

    # Medium (121-240)
    ("HIS130", "history", "Which battle fought in 1815 resulted in the final military defeat of French Emperor Napoleon Bonaparte?", "Battle of Waterloo", "Battle of Leipzig", "Battle of Austerlitz", "Battle of Trafalgar", "Battle of Waterloo", "The Battle of Waterloo in Belgium marked the end of the Napoleonic Wars.", "Easy"),
    ("HIS133", "history", "Which Roman Emperor legalized Christianity throughout the empire by issuing the Edict of Milan in 313 AD?", "Constantine the Great", "Augustus", "Nero", "Trajan", "Constantine the Great", "Constantine I granted religious tolerance to Christianity and relocated the capital to Constantinople.", "Easy"),
    ("HIS138", "history", "Which global conflict from 1939 to 1945 involved Allied and Axis powers and ended with atomic bombs dropped on Japan?", "World War II", "World War I", "Cold War", "Seven Years' War", "World War II", "World War II was the deadliest conflict in human history, concluding with Japan's surrender in 1945.", "Easy"),
    ("HIS143", "history", "Which West African ruler of the Mali Empire is widely considered one of the wealthiest individuals in human history?", "Mansa Musa", "Sundiata Keita", "Askia Muhammad", "Sunni Ali", "Mansa Musa", "Mansa Musa ruled the Mali Empire in the 14th century, famous for his lavish 1324 pilgrimage to Mecca.", "Medium"),
    ("HIS151", "history", "Which major wall structure was erected across northern Britain under Roman Emperor Hadrian in 122 AD?", "Hadrian's Wall", "Antonine Wall", "Servian Wall", "Aurelian Wall", "Hadrian's Wall", "Hadrian's Wall stretched 73 miles across Britain to consolidate Roman imperial frontiers.", "Medium"),
    ("HIS157", "history", "Which Chinese dynasty built significant unified sections of the Great Wall and standardized writing, currency, and weights?", "Qin Dynasty", "Han Dynasty", "Tang Dynasty", "Ming Dynasty", "Qin Dynasty", "Qin Shi Huang unified China in 221 BCE, founding the Qin Dynasty.", "Medium"),
    ("HIS162", "history", "Which historic peace treaty signed in 1919 officially concluded World War I between the Allied Powers and Germany?", "Treaty of Versailles", "Treaty of Utrecht", "Treaty of Westphalia", "Treaty of Ghent", "Treaty of Versailles", "The Treaty of Versailles imposed territorial losses and heavy war reparations on Germany.", "Medium"),
    ("HIS175", "history", "Which Mesoamerican civilization built the majestic step-pyramid temple of El Castillo at Chichen Itza?", "Maya Civilization", "Aztec Civilization", "Inca Civilization", "Olmec Civilization", "Maya Civilization", "Chichen Itza was a major regional capital built by the Maya civilization in Yucatan.", "Medium"),

    # Easy (201-240)
    ("HIS202", "history", "Which conflict from 1861 to 1865 was fought between Northern Union and Southern Confederate states in America?", "American Civil War", "American Revolutionary War", "War of 1812", "Mexican-American War", "American Civil War", "The Civil War preserved the United States Union and abolished slavery across the nation.", "Easy"),
    ("HIS205", "history", "Which ancient city-state in Greece was famous for its rigorous military culture and victory at Thermopylae against Persia?", "Sparta", "Athens", "Corinth", "Thebes", "Sparta", "Sparta was a prominent warrior society in ancient Greece renowned for disciplined hoplite phalanxes.", "Easy"),
    ("HIS209", "history", "Which historic event in 1789 marked the beginning of the French Revolution with the storming of a royal fortress?", "Storming of the Bastille", "Women's March on Versailles", "Execution of Louis XVI", "Tennis Court Oath", "Storming of the Bastille", "The Bastille fortress in Paris was stormed on July 14, 1789, symbolizing the end of royal absolutism.", "Easy"),
    ("HIS211", "history", "Which Mongol leader established the Mongol Empire in 1206 after unifying nomadic tribes of the Asian steppe?", "Genghis Khan", "Kublai Khan", "Tamerlane", "Batu Khan", "Genghis Khan", "Genghis Khan founded the largest contiguous land empire in world history.", "Easy"),
    ("HIS219", "history", "Which naval battle in 1571 saw the Holy League defeat the fleet of the Ottoman Empire in the Gulf of Patras?", "Battle of Lepanto", "Battle of Actium", "Battle of Salamis", "Battle of Jutland", "Battle of Lepanto", "The Battle of Lepanto halted Ottoman naval expansion in the western Mediterranean.", "Easy"),
    ("HIS230", "history", "Which English monarch established the Church of England in 1534 following a break with the Papacy in Rome?", "Henry VIII", "Elizabeth I", "Charles I", "Henry VII", "Henry VIII", "Henry VIII passed the Act of Supremacy making the monarch Supreme Head of the Church of England.", "Easy"),
    ("HIS232", "history", "Which South American empire built the high-altitude citadel of Machu Picchu in the Andes mountains?", "Inca Empire", "Aztec Empire", "Maya Empire", "Muisca Confederation", "Inca Empire", "Machu Picchu was constructed around 1450 under Inca Emperor Pachacuti.", "Easy"),
    ("HIS263", "history", "Which conflict between 1618 and 1648 devastated Central Europe before ending with the Peace of Westphalia?", "Thirty Years' War", "Eighty Years' War", "Seven Years' War", "War of Spanish Succession", "Thirty Years' War", "The Thirty Years' War began as a Protestant-Catholic conflict and reshaped European state sovereignty.", "Medium"),
]

print(f"Generated Science replacements: {len(sci_replacements)}")
print(f"Generated History replacements: {len(his_replacements)}")

